apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "tt-device-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tt-device-plugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tt-device-plugin.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "tt-device-plugin.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: system-node-critical
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tt-device-plugin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: dev-tenstorrent
              mountPath: /dev/tenstorrent
              readOnly: true
            - name: hugepages
              mountPath: /dev/hugepages-1G
              readOnly: true
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: dev-tenstorrent
          hostPath:
            path: /dev/tenstorrent
            type: Directory
        - name: hugepages
          hostPath:
            path: /dev/hugepages-1G
            type: DirectoryOrCreate
